### ISSUE TITLE
Upstream Memcached dev package conflicts with IUS on Centos 6.5

### ISSUE THREAD

**Issue by RichieSM** [rackspace-cookbooks/stack_commons#103] opened 2015-01-20 15:11 UTC
The recipe phpstack::memcached fetches the upstream memcached cookbook from Opscode.

When using phpstack::application_php at the same time on Centos 6.5, this line causes a yum conflict and the converge fails:
https://github.com/opscode-cookbooks/memcached/blob/master/recipes/default.rb#L28

This is because phpstack::application_php adds the IUS repo (required for PHP 5.4+) but the Opscode cookbook tries to fetch libmemcached-devel from the standard Centos repo.
Yum finds the newer version in IUS then exits with code 1.

**Comment by prometheanfire** [comment] 2015-03-26 15:04
I tested by running phpstack:application_php before and then after stack_commons:memcached and was not able to reproduce

closing :D

**Closed** 2015-03-26 15:04 UTC
